### PR TITLE
Create chromeos.md

### PR DESCRIPTION
**Pull request by perguth**
Bec why not 🤷‍♂️

### CODE REVIEW

**Comment by kylerchin** [comment]
Attempted to recreate, there are multiple bugs: "lxc config device add penguin tun unix-char path=/dev/net/tun`" is removed after every restart and the systemctl files are also deleted every restart.

**Comment by cjdelisle** [comment]
I've merged this to crashey, it should go to master in the next release which I expect to perform today, thanks for your contribution !

**Comment by perguth** [comment]
@kylerchin If you find a way how to get around the "restart and redo" issue, let me know :D

@cjdelisle 👍

**Comment by perguth** [comment]
@kylerchin This I use to spare me the reload part after adding the device to linux, maybe it helps you too. Just replace `yggdrasil` with `cjdns` then it should work: https://github.com/perguth/yggdrasil-chromeos/blob/master/README.md#install-a-helper-service

I wonder how we can fix the loss of `tun0` on every restart or auto add it. 🤔

**Comment by perguth** [comment]
For me (ChromeOS Beta, Version 75.0.3770.61) re-adding the `tun` device is no longer necessary. Gone for you too @kylerchin ?

**Pull request closed without merging**
