### PR TITLE
Fix Bencoding bug

### PR DESCRIPTION
**Pull request by dansup**
Fix the broken bencoding implementation of the cjdns admin api

### CODE REVIEW

**Comment by dansup** [comment]
I should have made it clear this is for the php admin library in .contrib.

**Comment by thefinn93** [comment]
:+1:

**Comment by cjdelisle** [comment]
Ok so I understand well you just took an entirely different bencode lib and
replaced the existing one?

On 01/15/2015 03:54 AM, Finn wrote:
> :+1: 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/cjdelisle/cjdns/pull/722#issuecomment-70032605
> 

-- 
Satire is the escape hatch from the cycle of sorrow, hatred and violence. #JeSuisCharlie

**Comment by dansup** [comment]
Yes, I replaced it with a different bencoding library and [fixed it](https://github.com/dansup/cjdns/blob/master/contrib/php/Bencode.php#L178-186), I also [updated](https://github.com/dansup/cjdns/blob/master/contrib/php/Cjdns.php#L93) the cjdns lib that @thefinn93 wrote.

**Comment by cjdelisle** [comment]
merged to crashey, thanks

**Pull request closed without merging**
