### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by rjmalagon**

### CODE REVIEW

**Comment by rjmalagon** [comment]
Anothes document spanish translation

**Comment by cjdelisle** [comment]
Merged all of the PRs to crashey but I squashed them together because it's a zillion patches which all do the same thing. Thanks !

**Comment by rjmalagon** [comment]
Thanks, sorry for being to verbose. I will try to make patches from a local
copy in my workstation and push in one piece.
I have little experience with the github site.

**Comment by cjdelisle** [comment]
No problem, thanks for contributing :)

**Pull request closed without merging**
