### PR TITLE
[WIP] Peer name fixes

### PR DESCRIPTION
**Pull request by kyrias**
[Reviews wanted]

### CODE REVIEW

**Comment by kyrias** [comment]
Have been running this branch on my 3 boxes for ~3 months now. (Thanks @lgierth for poking me about that.)

**Comment by cjdelisle** [comment]
This was fixed a different way in the cjdcmd branch, it's really just a few lines of code to change but you have to know where they are....

**Comment by kyrias** [comment]
I assume you mean the cjdnsctl branch, though it segfaults for me.  You sure it supports setting the name for the incoming connections as well?

Doesn't help that `peerName`, `login`, and `user` are used for multiple things in different parts of the codebase as well... >.>

**Comment by cjdelisle** [comment]
check branch cjdnsctl, this should be fixed there. Anyway unfortunately this fix is too complicated to accept.

**Comment by kyrias** [comment]
Well, as I said I did try cjdnsctl, and it still segfaults, and it's a bit hard to check the contents of the actual commits due to the multiple big wip commits, but fine.

**Comment by cjdelisle** [comment]
if you can catch me a backtrace, that would be very nice, I have been hunting an evasive segfault but I can't seem to repeat it...

**Comment by kyrias** [comment]
```
#0  0x000055555555f288 in List_size (list=0x55555585a328) at benc/List.c:33
#1  0x00005555555bf925 in ethInterface (config=0x555555837d38, ctx=0x7fffffffe1c0) at client/Configurator.c:389
#2  0x00005555555c135d in Configurator_config (config=0x7fffffffe230, sockAddr=0x7fffffffe410, 
    adminPassword=0x555555837db8, eventBase=0x5555558355c8, logger=0x55555583c138, alloc=0x555555835038)
    at client/Configurator.c:646
#3  0x00005555555c6af0 in main (argc=1, argv=0x7fffffffe5d8) at client/cjdroute2.c:712
```

**Pull request closed without merging**
