### PR TITLE
fix for 4.x kernels

### PR DESCRIPTION
**Pull request by John4782**

### CODE REVIEW

**Comment by lgierth** [comment]
Interesting, what problem are you attempting to fix?

**Comment by John4782** [comment]
I was trying to compile cjdns on Arch Linux and the test fails due to an error with seccomp. Recent kernels don't seem to allow a higher return value than 4096 (9000 in the code), so this is a working solution.

**Comment by alexander255** [comment]
Thanks for letting me know that this seccomp issue isn't my fault!

@lgierth I can confirm that this issue is also present with Ubuntu 4.0 lowlatancy mainline kernel.

**Comment by John4782** [comment]
This pull request has already been implemented into the crashey-branch, so you could pull that one and it should compile just fine on the affected kernels.

**Comment by alexander255** [comment]
Working now, thanks! :-)

**Pull request merged**
