### PR TITLE
Garmmar fix (and working on Afrikaans translation of README)

### PR DESCRIPTION
**Pull request by deavmi**
* Grammar fix adds `is`.
* Begun work on Afrikaans version of README

### CODE REVIEW

**Comment by cjdelisle** [comment]
I don't see really a serious translation to Afrikaans, just a few headings, I can't pull because of the risk that the job doesn't ever actually get done.

**Comment by deavmi** [comment]
I will continue to work on it.

**Comment by deavmi** [comment]
nvm.

**Comment by deavmi** [comment]
Just close the pr then. I can find someone that can do a WAAAY better 
job than me.

**Comment by cjdelisle** [comment]
ok

**Comment by deavmi** [comment]
:)

**Pull request closed without merging**
