### PR TITLE
Update README_GR.md

### PR DESCRIPTION
**Pull request by kaotisk-hund**
Updated greek version of README file, according to changes in #944 pull request.

### CODE REVIEW

**Comment by kaotisk-hund** [comment]
Last commit is not a translation. I didn't figure out how to make separated pull request for that.

**Comment by kaotisk-hund** [comment]
I changed the title :-)

**Comment by kyrias** [comment]
PRs should be sent from separate branches for each set of changes.

**Comment by cjdelisle** [comment]
merged to crashey, thanks

**Pull request closed without merging**
