### PR TITLE
Return hostnames support (disabled by default)

### PR DESCRIPTION
**Pull request by sssemil**
Return hostnames support but keep it disabled. It's kinda ok to have it on laptop. And maybe someone will add IP change detecting or whatever.

### CODE REVIEW

**Comment by kyrias** [comment]
I'm highly against this unless you fix one of the biggest reasons it was originally removed, being that it's quite buggy as it is.

It needs to check whether it's in an IPv4 block or IPv6 block and only resolve the details for the appropriate one, because currently it'll try to use IPv4 results as IPv6 addresses and IPv6 results as IPv4 addresses, and you get nice crashes from it.

**Comment by sssemil** [comment]
I'm not C++ dev but I'll try. Anyway that's why I put it under ifdefs.

**Comment by kyrias** [comment]
Well it's C not C++, and having it under a macro guard doesn't really justify adding back known broken code.  I was originally working on making it resolve things properly, but propagating the info in properly was hairy enough that it just didn't feel worth it at all considering that it's not really that useful in the first place.

It's much simpler to just have a program that generates a proper config before starting cjdroute, or one that uses the admin API to add the peers, possibly continuously resolving the domain and adding it as a new peer if necessary.

Alternatively writing a new cjdns client instead of cjdroute2.

**Comment by sssemil** [comment]
Oops. I see what you mean. Are there any good clients for admin interface with GUI?

**Comment by kyrias** [comment]
None that I've used, but there's e.g. [thefinn93's cjdns-php-gui](https://github.com/thefinn93/cjdns-php-gui) that might still work, but I can't say for sure.

**Comment by sssemil** [comment]
Thanks for looking but it's too insecure.

**Comment by sssemil** [comment]
No need for this guy.

**Pull request closed without merging**
