### PR TITLE
Python2 is no longer avaliable. Replaced with python.

### PR DESCRIPTION
**Pull request by kylerschin**

### CODE REVIEW

**Comment by cjdelisle** [comment]
Does `python` mean python3 now ?
Because if it does then we have a big problem, gyp (builder for libuv) requires python2.

**Comment by kylerschin** [comment]
No.  python means version2, while python3 means version3. I was fixing some docs, as this could be bad for some beginners,

**Comment by kylerschin** [comment]
@kpcyrd It did. That was back in the old days. 2012 to be precise.
Alright, enough with the yit yat. JUST MERGE IT!

**Comment by cjdelisle** [comment]
Merged to crashey, thanks !

In the future you can make PRs directly to crashey branch which makes it easier.

**Pull request closed without merging**
