### PR TITLE
Create contrib/edgerouter/README.md

### PR DESCRIPTION
**Pull request by neilalexander**

### CODE REVIEW

**Comment by wfleurant** [comment]
Hi Niel, the `./contrib` directory is mostly housing scripts but, we could certainly use this document at the [hyperboria/docs](https://github.com/hyperboria/docs/tree/master/install) repository. Could you possibly redo the pull-request with the document named `edgerouter.md` or `edge-os.md` or `ubiquiti-edgeos.md` instead?

**Comment by neilalexander** [comment]
Yes, gladly. I will close this pull request and submit another.

**Comment by wfleurant** [comment]
@neilalexander I apologize -- I did not even see all of the work in vyatta-cjdns. This should go in (preferably) hyperboria/cjdns (master) first, then the hyperboria/cjdns community reviews and makes a PR to  cjdelisle/cjdns (crashey).. Apologies! Looking forward to testing this out!!

**Comment by neilalexander** [comment]
@wfleurant No problem - where abouts in the hyperboria/cjdns repository would be sensible? In ./doc/install/ or some other location?

**Comment by wfleurant** [comment]
May be set it to land `./cjdns/doc/install/ubiquiti-edgeos.md` -- There's semi-related Ubiquiti docs (in openwrt.md) in there now so having the build info and link to your `vyatta-cjdns` project is even better. Thanks again.

**Comment by neilalexander** [comment]
Please see hyperboria/cjdns#132. Happy to contribute!

**Pull request closed without merging**
