### PR TITLE
Fix map loop

### PR DESCRIPTION
**Pull request by madafoo**
Stupid typo cause put map value hash2 function not equal with indexForKey map hash2 function.
Also add missing map fuzzing testing.

### CODE REVIEW

**Comment by madafoo** [comment]
still need fix some code, submit later.

**Comment by kpcyrd** [comment]
@madafoo you can continue to push commits to your branch and they get included in your PR :)

**Comment by wfleurant** [comment]
What does this code do? It hits a one or two minutes after cjdroute starts?

**Comment by Kubuxu** [comment]
@wfleurant madafoo added optimization to maps but there is some logical error causing lookup to randomly go into infinite loop causing total freeze.

**Comment by wfleurant** [comment]
@madafoo i tried your fix_map_loop branch and get this after a few minutes w/ 20+ peers more or less.. multiple interfaces, eth and udp.. 

```
#0  __memcmp_sse4_1
#1  Map_OfSessionsByIp6_compare (keyB=<optimized out>, keyA=0x7fffffffaa20) at ./util/Map.h:61
#2  Map_OfSessionsByIp6_put (map=0x55555580c428, value=0x7fffffffa988, key=0x7fffffffaa20) at ./util/Map.h:278
```

**Comment by madafoo** [comment]
@wfleurant Thanks for your test case I missed before, please re-test using the fix_map_loop branch.

**Comment by wfleurant** [comment]
Working well now @madafoo ```cjdns-v17.1-92-g7625296``` thanks to you!

**Comment by wfleurant** [comment]
@madafoo can you make a PR off branch hyperboria/cjdns

**Pull request closed without merging**
