### PR TITLE
Update osx.md

### PR DESCRIPTION
**Pull request by pguth**
- Log CJDNS output
- Use syntax highlighting

### CODE REVIEW

**Comment by kylerschin** [comment]
Thanks for the highlighting! We need more of this!
Any more changes?
Other than that, It's good to go!

**Comment by kylerschin** [comment]
Support for OSX is weak right now. Many Mac Developers like cjdns but can not install / use it properly.

**Comment by kpcyrd** [comment]
@kylerschin cjd is running cjdns on OSX. Are you on irc (irc.fc00.io/#cjdns)? I've never seen you there :)

**Comment by benhylau** [comment]
The brew install works quite well for me, what's wrong?

**Comment by kylerschin** [comment]
The instructions are difficult and rely on brew. My friend had trouble, he is a beginner at CJDNS.

**Comment by kylerschin** [comment]
I can't really see how to use the brew honestly.

**Comment by kpcyrd** [comment]
@kylerschin would you mind joining irc? :) I've only seen you semi-officially commenting on github so far, we might be able to help you with lots of your cjdns questions. (@pguth sorry for offtopic).

**Comment by benhylau** [comment]
Install with [Homebrew](http://brew.sh):

    brew install cjdns
    cjdroute --genconf > cjdroute.conf

Add a [public peer](https://peers.fc00.io) to **cjdroute.conf**:

    sudo cjdroute < cjdroute.conf

**Comment by cjdelisle** [comment]
Merged to crashey branch, thanks for the help and this will hit master in next release.

**Pull request closed without merging**
