### PR TITLE
Add a minimal man page for cjdroute.

### PR DESCRIPTION
**Pull request by wiml**
This just adds a basic manual page for the `cjdroute` command.

### CODE REVIEW

**Comment by cjdelisle** [comment]
This looks nice, @sdgathman do you know if there is any work done on a man page for Fedora ?  Maybe these two efforts could be merged (?)

**Comment by wiml** [comment]
> a man page for Fedora?

Ah, I didn't see that (PR #925 from a few years ago). Looks like it was accepted to a branch but never merged to trunk?

**Comment by cjdelisle** [comment]
I think it was merged and then later on those files were removed or renamed later, but I can't see when. I'll be happy to pull your contribution then. Thanks for making the effort !

**Comment by cjdelisle** [comment]
I've merged to the `crashey` branch, that's the development and staging branch for cjdns, it will go out in the release of v21.0, Thanks!

**Comment by wiml** [comment]
Thank you! I'd be happy to make man pages based on those markdown files as well, if that'd be desirable.

(IMHO it makes sense to keep the bulk of the docs in markdown, but each command should have at least a basic man page so people know where to look for more.)

**Comment by sdgathman** [comment]
> This looks nice, @sdgathman do you know if there is any work done on a man page for Fedora ? Maybe these two efforts could be merged (?)

The Fedora man page for cjdroute is in contrib/doc along with some other commands.

**Pull request closed without merging**
