### PR TITLE
Added useful address calculation code to lua contrib scripts

### PR DESCRIPTION
**Pull request by 4L3Xx**

### CODE REVIEW

**Comment by cjdelisle** [comment]
merged to crashey, to be merged into master during next release

**Comment by lgierth** [comment]
Nice, thanks! That means I can remove `publictoip6` from the OpenWrt package.

**Comment by wfleurant** [comment]
Re OpenWrt: Dependency check for bit32 and speed changes of publictoipv6 C
vs. pure Lua resolution. Thanks Alex

**Comment by 4L3Xx** [comment]
I didn't do a whole lot of testing, so, I would appreciate if someone could test it out some more.
Also, I think bit32 is native to Lua 5.2.  You only need big32 module if you are running 5.1.

**Comment by Kubuxu** [comment]
And it `bit32` might be also missing in Lua 5.3.

**Pull request closed without merging**
