### PR TITLE
Update ubuntu-16.04.md with build-essential dependency

### PR DESCRIPTION
**Pull request by kylerchin**

### CODE REVIEW

**Comment by kylerchin** [comment]
poke.

**Comment by kylerchin** [comment]
@cjdelisle please merge this... Please....

**Comment by iczero** [comment]
@kylerchin i think he's away from his computer or something, My PR has been open for 13 days and still not merged.

By the way, you might want to consider doing git pull --rebase to prevent the merge commits.

**Comment by kylerchin** [comment]
@iczero what @cjdelisle needs is more trusted maintainers that can review, merge, and help grow the cjdns community and that can commit ~10min on a daily basis.

**Comment by merkjinx** [comment]
yeah someone going to have to start some active development on cjdns. its about the best meshnet software i've ever seen.

**Pull request merged**
