### PR TITLE
Generalise node_build command flags and clean-ups

### PR DESCRIPTION
**Pull request by da2ce7**
This commit is a significant overhall of the main make.js file making the build system much more easily extendable.

Please merge after: https://github.com/cjdelisle/cjdns/pull/832

Fixes/Changes included:

* add 's' argument to ar, removing the need for ranlib 035ea412ddc54934180a759a431c617021a11256

* remove unused function in cnacl make.js 1f30e56734ab7d7d63bc824e743f955296081959

* correctly generate opi headers for cnacl  8b50ebce58e7963cf4114e6e487fa7ccce01dd00

* make processor detection consistent in build system 3707356429b05b60a2a534e4e0d2c3a9b0e11abb

* generalise node_build command flags and clean-ups fdc1bbbcaf5152ce31bae74a8526404b2ce2fb0a

One Fixup:

* make error handling in builder.js slightly better bf2338fd06a41c6cb3836746e8daf241ef27e39d

Please review each of these commits individually.  -  Any of these pull commits can be made into an individual pull request if needed.

Please test on other systems, I hope I haven't broken the build for anyone.

### CODE REVIEW

**Comment by da2ce7** [comment]
Hmm... the CI failed. Let me please investigate.

**Comment by da2ce7** [comment]
Ok, there is an issue with `make processor detection consistent in build system d825dfd8d4f5a7ccfefb46cace61c7561e6eace4`

Travis-ci shows many many threads, so much that it breaks the build.  I will try and debug.

**Comment by da2ce7** [comment]
ok, all CI checks passing. :)

**Comment by da2ce7** [comment]
@cjdelisle I just noticed that you have reverted my set of patches.
https://github.com/cjdelisle/cjdns/commit/8f706918bbf9a87fa71f3de9b163cec8c2c99ed2

I'm very sorry that they have caused issues for you.  However I placed them into three pull requests for interdependent review; however you merged all three at once; I assumed that you did review on each prior.

The first pull request https://github.com/cjdelisle/cjdns/pull/831 was a format-only change; no code paths should have been modified with this request.

The second https://github.com/cjdelisle/cjdns/pull/832 built upon the previous should be a refactor-only, the logic should be identical, however written differently.

The third pull request, this request, is very-much not "style only" changes. - It contains considerable logic changes to the build process, very likely containing untested bugs.  (I did my best to test, however I only have limited systems to test upon).  I was surprised that you merged this pull request so quickly, as it is indeed a considerable set of changes.

It would really help me if you could specify what actual commit caused your issues so that I may debug the problem. - It would also be helpful if you could send me a email so that I may have a chance to debug/fix any bugs before my changes are reverted.

**Comment by cjdelisle** [comment]
What is your objective in making these changes?

When I started to have problems with the build (which manifested themselves as a broken commit that the compiler didn't properly warn me about)
I reverted everything of yours then checked if it was working.
When it was I did a cost/benefit analysis which ended rather quickly because I see no benefit to your changes, only cost.

This is why I asked what is your objective.

If you intend to seperate this build system out into it's own general purpose project, that would be great.
There are times when I would like to write something other than cjdns and I want to use some of my generic code,
which is currently not possible without copy/pasting it over, and in order for it to build, it needs the js preprocessor step.

If that's your end objective then I say "go for it", split the build system off and when it's stable I'll try to port cjdns over to using it.

If your objective is just to "clean up", I'm sorry but you're going to have to learn to love the dirt.

**Comment by da2ce7** [comment]
@cjdelisle Thank you for your response.

I have ported the cjdns build-system to the Microsoft Visual C compiler.
https://github.com/da2ce7/cjdns/commit/1d7ee21eeb05d89de9c7fadaf18b95cd8370efab
https://github.com/da2ce7/cjdns/commit/bfdd9a0ad9e0e6caf8c34fcbaa154b0cdfb83cc0

(and lots of commits for small bug-fixes in the .c code)
I haven't made this code public as it is still a work-in-progress.

This pull request is the back-port of any generic bug/cleanup that I fixed/made when porting the build-system. - Here is the ported `node_build` with all the msvc-only code striped out.

Because of the large amount of code-changes, and the need to regularly re-base. (maybe in a private msvc feature branch).  I wished to first move the code into a consistent style. Hence PR https://github.com/cjdelisle/cjdns/pull/831 and PR https://github.com/cjdelisle/cjdns/pull/832 .

The remaining commits are generic versions of the fixes that I had to apply to enable msvc support.

I wasn't going to bother you about the msvc support until it was stable and reliable. - However I thought that it was opportunistic to back-port any useful changes along the way. (also minimizing the patch-set that I have to maintain while msvc support stabilizes).

My end-goal is: first-class windows support; additional static-analysis from another compiler; and an overall improvement to the compiler infrastructure.

**Pull request merged**
