### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by madafoo**
unsetupSession do not function because typo make DHT ping always send wrong path.

### CODE REVIEW

**Comment by ProgVal** [comment]
I don't see the difference when either `sess->pub.sendSwitchLabel` or `sess->pub.recvSwitchLabel` is nonzero.
And if both are zero, `path_be` is undefined memory instead of zero after your patch.

**Comment by madafoo** [comment]
Please check https://github.com/cjdelisle/cjdns/blob/crashey/net/SessionManager.c#L455.

sess->pub.sendSwitchLabel & sess->pub.recvSwitchLabel could not be both zero.

**Comment by ProgVal** [comment]
Then I don't see how your patch changes the behavior of the code.

**Comment by madafoo** [comment]
because (sess->pub.recvSwitchLabel || sess->pub.sendSwitchLabel) = 1 but not the real path.

**Comment by ProgVal** [comment]
Oh indeed. Sorry, I confused C's semantics with Python's. (In Python, `a or b` is equivalent to `a if a else b`.)

**Comment by madafoo** [comment]
Yep, I think cjd wrote the code here confused C's semantics with Javascript's. So it is a typo.

**Pull request merged**
