### PR TITLE
Tunnel removeConnection typo

### PR DESCRIPTION
**Pull request by madafoo**

### CODE REVIEW

**Comment by kylerschin** [comment]
Thanks @madafoo! I'm Wondering if it's causing this problem:

        1474346755 DEBUG Core.c:312 Finished getting pre-configuration from client
        1474346755 DEBUG UDPAddrIface.c:254 Binding to address [127.0.0.1:11234]
        1474346755 DEBUG UDPAddrIface.c:293 Bound to address [127.0.0.1:11234]
        1474346755 DEBUG UDPAddrIface.c:293 Bound to address [0.0.0.0:56380]
        1474346755 DEBUG AdminClient.c:333 Connecting to [127.0.0.1:11234]
        1474346755 INFO Configurator.c:135 Checking authorized password 0.
        1474346755 INFO Configurator.c:159 Adding authorized password #[0] for user [default-login].
        1474346760 CRITICAL Configurator.c:97 Failed to make function call [Timed out waiting for a response], error: [UDPInterface_beginConnection]
        1474346760 CRITICAL Configurator.c:57 enable Log_LEVEL=KEYS to see message content.
        1474346760 CRITICAL Configurator.c:71 Aborting.

**Comment by madafoo** [comment]
Seems not related. Did you meet this problem after apply my patch?

**Comment by kylerschin** [comment]
@madafoo nope.

**Comment by cjdelisle** [comment]
nice catch, thanks mada!

**Pull request merged**
