### PR TITLE
README.md: Adding Gentoo instructions.

### PR DESCRIPTION
**Pull request by Weuxel**

### CODE REVIEW

**Comment by kylerschin** [comment]
Well, Thanks! I do not understand the slightest on how Gentoo works. Thank You.

**Comment by cjdelisle** [comment]
Thanks and I know I asked for this but the issue is it's based on an old enough version that I don't want to recommend it so I'm hoping uniaika can update it with her gentoo script which I completely don't understand...

**Comment by lonewolf9277** [comment]
Ok will check this out

**Comment by Weuxel** [comment]
For starters i have updated my repo to latest master.
https://github.com/Weuxel/portage-weuxel/tree/master/net-misc/cjdns
If desired, i could change the readme to use this.

An official gentoo repository would be great. Are there plans for this?

**Comment by cjdelisle** [comment]
If you have an up-to-date version then I'll happily merge with that. 2 major releases behind is hard for me to accept.

**Pull request closed without merging**
