### PR TITLE
Seasonal Change

### PR DESCRIPTION
**Pull request by benhc123**
No longer October

### CODE REVIEW

**Comment by kylerchin** [comment]
+1

**Comment by 8341696379** [comment]
Please consolidate #1126, #1127, #1128, #1129, #1130, #1131 and #1132 into a single pull request...

**Comment by benhc123** [comment]
@8341696379 Hi there. I would do that if these pull requests were distinct enough. I'm also in the web version of GitHub so I'm not certain how combine commits. Also, who are you? I notice that you have never made any commits to this repository, have no profile photo and have a string of numbers as your username. Are you asking on behalf of the project's maintainers? 😕

**Comment by 8341696379** [comment]
@benhc123 You can do this easily through the web interface: fork the repository, make the changes you want and finally, create the pull request to crashey branch.

**Comment by cjdelisle** [comment]
Given that there is a tip4commit pot which pays out to people for each commit, it is rude to make a whole lot of micro-commits and take many times what another person would take for a single commit fixing a significant bug. Please consolidate all of your contributions if you would like to make them.

**Pull request closed without merging**
