### PR TITLE
Make cjdns build for arm64 android device

### PR DESCRIPTION
**Pull request by madafoo**
usage:
cd contrib/android
TARGET_ARCH=arm64  ./cjdroid-build.sh

### CODE REVIEW

**Comment by madafoo** [comment]
This patch make cjdns for android arm64 build work, but it remain some known bug: the seccomp function can not work, I have to disable seccomp feature to let the cjdns run on the arm64 android device.

**Comment by kyrias** [comment]
Eg Samsung disables SECCOMP support in their kernels, wouldn't surprise me if others did as well. Which device have you tested on, and with the stock or custom ROM?

**Comment by madafoo** [comment]
Lenovo K50-t5

**Comment by lgierth** [comment]
Looks good to me :+1:

**Comment by kyrias** [comment]
@madafoo You wouldn't happen to have access to the kernel config?

**Comment by cjdelisle** [comment]
We should look at a patch-based solution so that updating the version of libuv is less annoying

**Comment by lgierth** [comment]
> We should look at a patch-based solution so that updating the version of libuv is less annoying

Yeah we really should -- I think we're at a dozen or so patches now, plus the stuff for windows.

**Pull request merged**
