### PR TITLE
Fix compile on gentoo

### PR DESCRIPTION
**Pull request by svirusxxx**
Hi,
I have some problems witch compiling cjdns on my gentoo.
After few fix it's works for me.

### CODE REVIEW

**Comment by lgierth** [comment]
Looks good, except for the removed warning in Seccomp.c -- you should probably build with Seccomp_NO=1 instead.

**Comment by svirusxxx** [comment]
OK, I restored warning , and added info about this variable.

**Comment by cjdelisle** [comment]
merged to crashey, will release to master in the next release

**Comment by ehmry** [comment]
@svirusxxx I have an ebuild for Gentoo that I (try to) maintain, let me know if you want to see any changes or if it needs to be bumped.
https://cgit.gentoo.org/user/emery.git/

**Comment by svirusxxx** [comment]
@ehmry I tried this ebuild from your overlay, but I have same problem.
Try to add ebuild witch git (-9999 version).
Also will be nice to add check for seccomp or just add USE flag to ebuild.

**Comment by ehmry** [comment]
@svirusxxx if you have time please vote/complain that an ebuild should get in the main tree
https://bugs.gentoo.org/process_bug.cgi

**Pull request closed without merging**
