### PR TITLE
Update install instructions for macOS

### PR DESCRIPTION
**Pull request by l2dy**

### CODE REVIEW

**Comment by kylerschin** [comment]
I guess... Cool.

**Comment by kpcyrd** [comment]
@kylerschin could you please stop spamming?

**Comment by benhylau** [comment]
@l2dy I would say either update this on all translations of the README or none.

**Comment by kylerschin** [comment]
I have a friend @weijingwang who I introduced CJDNS to. He set it up on all his servers, but he carries a macbook pro from 2013 with him for school. Is there any documentation on how to install using brew? We have brew installed, but I don't know where to go after that.

**Comment by l2dy** [comment]
@benhylau I've updated the PR but they are already out of sync. README_RU.md didn't even mention OS X and README_HR.md mentioned Homebrew to install dependencies.

@kylerschin See https://brew.sh/ and http://docs.brew.sh/.

**Pull request merged**
