### PR TITLE
License header in scripts

### PR DESCRIPTION
**Pull request by mangeurdenuage**
Hello,
I'm working as a volunteer for the Free Software Directory. 
Your program is free software so in principle it should be listed there, and I'd like to add it.
But it has some problems in showing what its license is.

Some Bash script files don't have a license header.
Could you or someone else in the project be kind enough to add them in the files please, for the sake of users and other developers? ?
For example the files "cjdroid-build.sh" in "cjdns-master/contrib/android"

If you are interested in the FSD your project is referenced here:
https://directory.fsf.org/wiki/Cjdns

### CODE REVIEW

**Comment by kyrias** [comment]
@mangeurdenuage Why is this a PR trying to merge cjdnsctl into master?...

**Comment by mangeurdenuage** [comment]
Because I am not a user of git thus I made a mistake.
I simply don't know how to address it correctly.

**Comment by cjdelisle** [comment]
Ouch, what were you trying to change here ?
It looks like you accidently made a billion zillion changes because Git Is Hard.
Perhaps you could take a fresh clone and do `git checkout crashey`, make your changes and then type `git diff` and paste the resulting content here.

Thanks very much for your help on the project !

**Comment by kyrias** [comment]
@cjdelisle They didn't make any change at all, just opened a PR to merge your cjdnsctl branch.  They essentially just failed at opening a GH issue.

**Comment by cjdelisle** [comment]
ok, if as kyrias says, you have no changes to make then I'll just go ahead and close this PR.

**Pull request closed without merging**
