### PR TITLE
Long readme

### PR DESCRIPTION
**Pull request by wobbol**
resolve issue #718

### CODE REVIEW

**Comment by benhylau** [comment]
:+1: 

As you point out, we should also at some point fix [Step 3](https://github.com/cjdelisle/cjdns#3-connect-your-node-to-your-friends-node). I was pretty confused when I read that for the first time. Maybe just mention the easiest way to connect to Hyperboria, which is to find a friend willing to give you the creds, peer outbound and operate as a leaf node. Then jump straight to **Step 4**. The rest about letting people peer inbound can be moved to another section.

Still think we should move all this to **gh-pages**. The `README.md` can be just a single paragraph directing people to that page.

We should merge this PR for now.

**Comment by wobbol** [comment]
Shameless plug: I did a whole writeup yesterday in the documentation repo that covers this section and more.
[Here][] is my branch.
[Here]: http://gitboria.com/nicole/documentation/blob/peering-over-UDP-and-Eth/en/cjdns/peering-over-UDP-IP.md

**Comment by wobbol** [comment]
I thought it merged lol. I am going to bed now.

**Comment by cjdelisle** [comment]
merged to crashey, thanks

**Pull request closed without merging**
