### PR TITLE
Need python to build cjdns

### PR DESCRIPTION
**Pull request by nickodell**

### CODE REVIEW

**Comment by Aranjedeath** [comment]
I'm not aware of any part of the build process which uses python. What problem are you running into?

**Comment by nickodell** [comment]
@Aranjedeath This error:

```
done
testing python python
error starting python Error: spawn ENOENT
testing python python2
error starting python Error: spawn ENOENT
testing python python2.7
error starting python Error: spawn ENOENT
testing python python2.6
error starting python Error: spawn ENOENT
testing python python2.5
error starting python Error: spawn ENOENT
Total build time: 4000ms.

/root/cjdns/node_build/make.js:332
                if (err) { throw err; }
                                 ^
Error: no sutible python2 executable found ( < 2.7 unsupported)
    at /root/cjdns/node_build/FindPython2.js:52:18
    at /root/cjdns/node_modules/nthen/lib/nthen.js:20:30
    at ChildProcess.<anonymous> (/root/cjdns/node_build/FindPython2.js:42:21)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:755:16)
    at Process.ChildProcess._handle.onexit (child_process.js:822:5)

```

**Comment by Kubuxu** [comment]
Build of libuv requires gyp iirc.

**Comment by Aranjedeath** [comment]
Oh fml you're right @Kubuxu. 

@cjdelisle ping, merge pls

@nickodell I guess you're trying to build on Debian stretch? I think that's the only one which doesn't ship python2 by default

**Comment by lgierth** [comment]
Yeah I had to apt-get install python2.7 on a fresh ubuntu 16.04 the other day too

**Comment by nickodell** [comment]
@Aranjedeath Debian Jessie, actually.

**Comment by cjdelisle** [comment]
merged to crashey, thanks

**Pull request closed without merging**
