### PR TITLE
Some typos in the whitepaper

### PR DESCRIPTION
**Pull request by ether42**
Inadvertently closed #1056 while renaming the branch, sorry.

### CODE REVIEW

**Comment by ProgVal** [comment]
Could you update your PR to target the `crashey` branch?

**Comment by ProgVal** [comment]
Looks like you rebased on `crashey` instead. The target branch is specified on this page, just bellow the title.

**Comment by ether42** [comment]
I rebased then changed the destination branch (wasn't sure if GitHub would do the rebase automatically?).

**Comment by ProgVal** [comment]
The rebase was not necessary, nor does Github do a rebase automatically.
When merging branches `A` and `B`, both can have commits the other hasn't, it's not a problem. (It is called a non-fast-forward merge, and is the most common type of merge.)

**Comment by ether42** [comment]
Yeah but the the resulting commit graph is quite awful to look at without a rebase :)

**Pull request merged**
