### PR TITLE
Add /r/CJDNS

### PR DESCRIPTION
**Pull request by asdfghjz**
Added [/r/CJDNS](https://www.reddit.com/r/cjdns/) to Communities

### CODE REVIEW

**Comment by kyrias** [comment]
uh, so.

1) Remove the space after the URL.
2) Squash all of the garbage commits together.
3) This should be against the crashey branch.

**Comment by asdfghjz** [comment]
@kyrias I think I fixed it #1183 
I believe maintainers can edit and close this if they need any more changes.

**Comment by kyrias** [comment]
Well, you got 1 and 3 at least, but not 2.

**Comment by asdfghjz** [comment]
@kyrias sorry, how do I do that? (:-)

**Pull request closed without merging**
