### PR TITLE
sPELLING

### PR DESCRIPTION
**Pull request by deavmi**
sorry caps lock.

### CODE REVIEW

**Comment by cjdelisle** [comment]
This patch was merged into crashey branch, it will land in master at the next release. Thanks for your help !

**Comment by deavmi** [comment]
Pleasure mate :)

**Comment by deavmi** [comment]
BTW Keep up the absolutely amazing work. You artist.

**Comment by cjdelisle** [comment]
Thanks :D

**Comment by deavmi** [comment]
You inspired me to learn networking in depth and I am enjoying it. never 
knew how cool it was.

**Pull request closed without merging**
