### PR TITLE
Fix packaging

### PR DESCRIPTION
**Pull request by projektvpn**
The Ubuntu/Debian scripts were building packages that didn't install cleanly or work correctly.

### CODE REVIEW

**Comment by cjdelisle** [comment]
I'm not qualified to address this myself, on my fedora machine it is `/usr/bin/systemctl` though, I need someone else's advice about the rest.

**Comment by cjdelisle** [comment]
@sdgathman do you have an opinion ?

**Comment by rTreutlein** [comment]
On arch i got /usr/bin/systemctl and /bin/systemctl .

But it seems a bit strange to call systemctl from a systemd service.

**Comment by kpcyrd** [comment]
How about we install a script at a known location and call that instead?

> But it seems a bit strange to call systemctl from a systemd service.
Also +1 on that

**Comment by sdgathman** [comment]
On Fedora (and other LSB system) /usr/bin and /bin are symlinked.  As to calling systemctl from a service:
 a. it works
 b. the systemd project would be the place to ask if there is a better way

In the latest Fedora packaging, I create a ```/etc/cjdns/up.d``` directory, from which scripts are run when the cjdns interface comes up (which sadly, does not necessarily mean you have actual connectivity yet).  The resume function could be handled similarly.  You would still be calling systemctl from a systemd service - but indirectly!!  More importantly, it could be considered more obvious to an admin who needs to customize to modify a script in ```/etc/cjdns/resume.d``` than to copy a service to ```/etc/systemd/system``` and modify it.

**Comment by sdgathman** [comment]
I should point out that a systemd service directly calls ```exec()``` for its ```ExecStart``` entries.  Having systemd exec ```/bin/sh``` which then execs systemctl just adds overhead (and more security considerations as the shell script, the directory it resides in, and any other programs it calls all have to be secured).

If you think about it, all invocations of systemctl are done from systemd - just usually with more indirection.  For example, from a text console, systemd execs login, which execs bash, which (when you type the command) execs systemctl.  Generally, the less indirection, the more reliable (but less flexible).

**Comment by projektvpn** [comment]
Is there a real justification for having cjdns-resume.service at all? It seems to be a workaround for a bug in cjdns from over a year ago.

Another "fix" would be to drop the `Also` line from `cjdns.service`, and just deal with the user having to uninstall or install both manually if they are doing a manual setup. Then the Debian/Ubuntu packages could just ship `cjdns.service`.

**Comment by kpcyrd** [comment]
the correct way is probably detecting network changes directly, if I recall correctly "restart after suspend" was a workaround for that.

**Comment by sdgathman** [comment]
Yes, cjdns-resume is a workaround.  I will continue to include it in Fedora if it is removed until the need goes away.  There are indeed many other network changes that currently still require a manual restart.  Suspend/resume was just low hanging fruit that solves a very common use case.  I would consider cjdns-resume more of an "example" than something every distro should include.

There is a hook in NetworkManager that could be used to restart cjdns on network changes.  I think all that is required is to drop a script in /etc/NetworkManager/dispatcher.d that restarts cjdns on the "up" event for any interface.

**Comment by sdgathman** [comment]
I don't think it is reasonable for cjdroute itself to check for network changes.  Each distro should pick the best method for their setup.  For instance, requiring NetworkManager would not be correct either.

**Comment by kpcyrd** [comment]
@sdgathman a lot of distros don't enforce a specific network manager. For example you can run ubuntu with NetworkManager, but you can also just install wicd and use that. I think the correct way for a distro is supporting as many as possible, so they'd ship hooks no matter if the programm is installed or not.

**Comment by kylerschin** [comment]
@sdgathman @kpcyrd The beauty of linux is that you don't need to be stuck with one software. Don't like Ubuntu? Switch to Arch! Don't like gnome? Switch to budgie! etc.etc. However, also, the downside of this is that I can't make a snap for snapcraft.io :(

**Comment by cjdelisle** [comment]
@sdgathman should this PR be taken or closed ?

**Comment by sdgathman** [comment]
I think that cjdns-resume.service should be move to contrib/distro directories.  It is not really a part of cjdns itself, but a distro packaging detail.  I would recommend not applying the PR, debian people adding their version in contrib/debian, and I can add my version in contrib/fedora (or just add it in the fedora packaging).  Then you can just remove contrib/systemd/cjdns-resume.service.   (Or add a comment that it is an example only.)

I put it in contrib/systemd because I naively though systemd was standardizing this sort of thing somewhat.

**Comment by sdgathman** [comment]
BTW, I can't use cjdns.service as-is either.  I have to patch it with the Fedora location of cjdroute (and other changes).

**Comment by cjdelisle** [comment]
Thanks for your advice. @projektvpn basically if you can make @sdgathman happy then I'm happy to pull whatever results.

**Comment by sdgathman** [comment]
@projektvpn   The principle is that if we change it, it needs to be more distro-agnostic, not less.

**Comment by sdgathman** [comment]
I've been experimenting with cjdns in various mobile/mesh situations, and the upshot is that cjdns-resume is useless when your connection is changing.  What is needed on Fedora is a NetworkManager dispatcher script to restart cjdns when a new interface comes up (which *should* also handle resume -  I'll have to test).  But that is distro specific.  This supports the plan to deprecate cjdns-resume.

**Pull request closed without merging**
